azure:
  storage:
    account:
      blob-url: https://bbbb.blob.core.windows.net
      queue-url: https://qqqq.queue.core.windows.net
      token: <sas-token>
      blob-container: <blob-container>
  cosmos:
    url: https://cccc.documents.azure.com:443
    key: <key>
    database: <database>
    container: <container>

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <issuer-uri>